// Required Dependencies
const FyersAPI = require("fyers-api-v3").fyersModel;
const otplib = require("otplib");
const axios = require("axios");

// Constants
const BASE_URL = "https://api-t2.fyers.in/vagator/v2";
const BASE_URL_2 = "https://api.fyers.in/api/v2";
const URL_SEND_LOGIN_OTP = BASE_URL + "/send_login_otp";
const URL_VERIFY_TOTP = BASE_URL + "/verify_otp";
const URL_VERIFY_PIN = BASE_URL + "/verify_pin";
const URL_TOKEN = BASE_URL_2 + "/token";
const SUCCESS = 1;
const ERROR = -1;

// Function to send login OTP to the user's mobile number
async function sendLoginOTP(fy_id, app_id) {
    try {
        const response = await axios.post(URL_SEND_LOGIN_OTP, { fy_id, app_id });

        if (response.status !== 200) {
            return [ERROR, response.data];
        }

        const { request_key } = response.data;
        return [SUCCESS, request_key];
    } catch (error) {
        return [ERROR, error.message];
    }
}

// Function to verify the TOTP generated by the user
async function verifyTOTP(request_key, totp) {
    try {
        const response = await axios.post(URL_VERIFY_TOTP, { request_key, otp: totp });

        if (response.status !== 200) {
            return [ERROR, response.data];
        }

        const { request_key: newRequestKey } = response.data;
        return [SUCCESS, newRequestKey];
    } catch (error) {
        return [ERROR, error.message];
    }
}

// Function to generate the access token for Fyers API
async function generateAccessToken(FY_ID, TOTP_KEY, PIN, APP_ID, REDIRECT_URI,APP_SECRET) {
    const APP_ID_TYPE = "2"
    // value after - from appID
    const APP_TYPE = "100"

     // Step 1: Send login OTP
    const send_otp_result = await sendLoginOTP(FY_ID, APP_ID_TYPE);

    if (send_otp_result[0] !== SUCCESS) {
        console.log(`send_login_otp failure - ${send_otp_result[1]}`);
        process.exit(1);
    } else {
        console.log("send_login_otp success");
    }

    let verify_totp_result;
    // Step 2: Verify TOTP (up to 3 attempts)
    for (let i = 1; i <= 3; i++) {
        const request_key = send_otp_result[1];
        verify_totp_result = await verifyTOTP(request_key, otplib.authenticator.generate(TOTP_KEY));

        if (verify_totp_result[0] !== SUCCESS) {
            console.log(`verify_totp_result failure - ${verify_totp_result[1]}`);
            await new Promise((resolve) => setTimeout(resolve, 1000)); // Wait for 1 second before retrying
        } else {
            break;
        }
    }
    // Step 3: Verify PIN and obtain access token
    const request_key_2 = verify_totp_result[1];
    const ses = axios.create();
    const payload_pin = {
        "request_key": request_key_2,
        "identity_type": "pin",
        "identifier": PIN,
        "recaptcha_token": ""
    };
    const res_pin = await ses.post(URL_VERIFY_PIN, payload_pin);
    const ses1 = axios.create({
        headers: {
          'authorization': `Bearer ${res_pin.data['data']['access_token']}`
        },
        maxRedirects: 10,
      });
    const authParam = {
        "fyers_id": FY_ID,
        "app_id": APP_ID,
        "redirect_uri": REDIRECT_URI,
        "appType": APP_TYPE,
        "code_challenge": "",
        "state": "None",
        "scope": "",
        "nonce": "",
        "response_type": "code",
        "create_cookie": true
    };

     // Step 4: Generate the access token using the authorization code and secret key
    let authres
    try {
         authres = await ses1.post(URL_TOKEN, authParam);
    } catch (error) {
         authres = error.response
    }
    const url = authres.data['Url'];
    const parsed = new URL(url);
    const auth_code = parsed.searchParams.get('auth_code');

    var fyers = new FyersAPI()
    fyers.setAppId(`${APP_ID}-${APP_TYPE}`)
    fyers.setRedirectUrl(REDIRECT_URI)
    let akstkn;
    try {
        // Generate access token using the provided authorization code and secret key
        const tokenResp = await fyers.generate_access_token({ "secret_key": APP_SECRET, "auth_code": auth_code });
    
        // Check if access token generation was successful
        if (tokenResp.s == "ok") {
            // Set the obtained access token for further API calls
            akstkn=tokenResp.access_token
            fyers.setAccessToken(tokenResp.access_token);
        } else {
            console.log("Error generating accessToken:", tokenResp);
            process.exit(1);
        }
    } catch (error) {
        console.log(error);
        process.exit(1);
    }


    return [fyers, akstkn];
}

// Main function to execute the access token generation
async function main(){
    var FYID="xxxxxxx"
    var TotpKey ="xxxxxxxx"
    var Pin ="xxxx"
    var APPID="QC7T0H8425"
    var RedirectURL="https://xxxx.xxxxx.xxx"
    var AppSecret="Secret"
    var resp=await generateAccessToken(FYID,TotpKey,Pin,APPID,RedirectURL,AppSecret)
    var token=resp[1]
    console.log(token)
}


main()